### PR TITLE
Move to spork/argparse

### PR DESCRIPTION
**Pull request by pepe**
Also, I removed some trailing spaces per spork/fmt. If this would be a problem, let me know I will remove these changes from the PR.

### CODE REVIEW

**Comment by pepe** [comment]
I forgot to mention the purpose of this commit overall :). Standalone argparse is "deprecated" as we moved it to spork. Yet, there is no problem with using it, so feel free to close this PR if you do not want to move to spork.

**Comment by pepe** [comment]
So my bad, as I found that argparse was deprecated only in my mind. I created an issue on the argparse with the deprecation question. Sorry for all the fuss.

**Comment by ianthehenry** [comment]
Thanks! That's a good reminder that the trailing-space detector in my editor is broken.

I didn't know about `spork/fmt` -- I used it to autoformat most of the code to match that style. It doesn't support adding custom control forms yet so the examples are still unformatted, but I tried to match the canonical style as much as possible there too.

I assumed that `spork/argparse` just required and re-exported the standalone `argparse` module, but I see now that that isn't the case? It's actually just copied and pasted code? That's very confusing to me and feels like a step backwards. I feel kind of weird depending on a pretty large bundle of code just to get this one module -- it feels like a heavy dependency to bring into an otherwise lightweight testing library. Certainly a comment or something explaining what's going on there would be useful to newcomers like me.

Although I'll probably depend on it anyway just for `spork/fmt` -- it'd be nice to use that to pretty print results. I wish that it was also a standalone library, though. Neither of those have any dependencies on other pieces of `spork`, so I don't know why they're glommed together like that.

**Comment by pepe** [comment]
Hello. There is a forming habit of more extensive libraries in Janet. It seems bakpakin is a fan of this approach. If I can understand it well, it is no big deal. The only place where it could matter is binaries, but the code is tree shaken, and only the part you use in your program will end up in the binary.

I have spork in all my libraries, as I am using spork/test for unit tests, but I can understand it is no actual argument.

**Comment by pepe** [comment]
I will close this PR and let you decide. Cheers

**Pull request closed without merging**
